### ISSUE TITLE
Fix health-check listener monitor to accommodate the default 0.0.0.0 address

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-lib#2]
Ref. https://github.com/uhppoted/uhppoted/discussions/14

The health check listener address monitor checks the device listener address against the configured system listener address which fails when the configured listener address is set to the default _ALL_ address (0.0.0.0):
```
		if !expected.IP.Equal(address.IP) || (expected.Port != address.Port) {
                   ...
               }
```

(cf. [healthcheck.go:L385](https://github.com/uhppoted/uhppoted-lib/blob/master/monitoring/healthcheck.go#L385))

With the default _0.0.0.0_ address, the 'expected' health address check should match against at least:
- 127.0.0.1
- the public IPv4 address
- (optionally) a configured address

_Notes_
1. Ideally the health check should verify that the IP address to which the system event listener is bound is reachable via the controller's configured listener address.

**Comment by uhppoted** [comment]
Reworked health check to match controller listen address against all IPv4 addresses exposed by the installed network interfaces when the listen address is `INADDR_ANY` (_0.0.0.0_). Provisionally excludes the loopback address (_127.0.0.1_) on the grounds that the loopback address is probably only used by simulated devices.

Tested on _MacOS_ and _Ubuntu 22.04LTS_.

**Comment by uhppoted** [comment]
Fixed in [release v0.8.1](https://github.com/uhppoted/uhppoted-lib/releases/tag/v0.8.1)

**Comment by uhppoted** [comment]
Ref. https://github.com/uhppoted/uhppoted/discussions/14#discussioncomment-3312231

`netip.AddrFromSlice` is prefixing an IPv4 address with `:ffff:`:
````
2022/08/03 10:14:19 WARN  UTC0311-L0x 201020304  incorrect listener address/port: 192.168.1.100:60001
>>>>>>>> [192.168.1.100:60001]
>>>>>>>> DEBUG true ::ffff:192.168.1.100 60001
2022/08/03 10:14:19 WARN  UTC0311-L0x 303986753  incorrect listener address/port: 192.168.1.100:60001
```

Explicitly convert address to an IPv4 address before checking.

**Comment by twystd** [comment]
May possibly be related to changes in the `netip` package:

- [net: UDPAddr's (and possibly TCPAddr's) AddrPort returns addresses with the wrong IP version](https://github.com/golang/go/issues/53607)

**Comment by twystd** [comment]
Explicitly converted IP addresses to IPv4 addresses in the health check. Pending confirmation and release.

**Comment by uhppoted** [comment]
Closing - release in [v0.8.2](https://github.com/uhppoted/uhppoted-lib/releases/tag/v0.8.2)
